<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <script>
        /** 1. */
        function getCountry(countryName){
            fetch(`https://restcountries.com/v2/name/${countryName}`)
            .then(response => {
                if (!response.ok){
                    return;
                }
                return response.json();
            })
            .then(country => console.log(country[0]))
            .catch(err => console.log("err...",err))
        }
       getCountry("mauritius");
    </script>



    <script>
        /** 2. Return value from fetch using callback*/
        function getUsers(callback){
            fetch("https://jsonplaceholder.typicode.com/users")
            .then(response => response.json())
            .then(users => callback(users))
            .catch(error => callback(undefined))
        }

        getUsers(function(args){
            if (!args){
                return
            }
            console.log(args)
        });
    </script>



    <script>
        /** 3. Chaining promises */
        function getCountryDetails(country){
            fetch(`https://restcountries.com/v2/name/${country}`)
            .then(response => response.json())
            .then(country => {
                const neighbour = country[0].borders[0];

                if (!neighbour){
                    return;
                }

                fetch(`httpst://restcountries.com/v2/alpha/${neighbour}`)
                .then(response2 => response2.json())
                .then(neighbourdetails => console.log("neighbourdetails", neighbourdetails))
            })
        }
        getCountryDetails("spain");


    </script>



    <script>
        /** 4. Await and fetch */
        function display(){
            return "Hello";
        }

        async function getAnotherCountry(){

            try {
                // 1.
                let response = await fetch('https://restcountries.com/v2/name/france')
                let country = await response.json();
                console.log(" ------ country[0]", country[0]);

                const res = display();
                console.log("----- res ", res);

            } catch (error) {   
                console.log("catch error ", error);
            }
        }
        getAnotherCountry();

        /**
         *  5.
         *  If not try...catch
         *  We can alternatively append .catch() on the promise generated by the async function. 
         *  Let's recap: Remember that the async function returns a promise. 
         *  If an error occurs then it returns a rejected promise.
         *  So on the function call we could do this:
         * 
         */
         async function asyncFunct(){
            let response = await fetch('https://restcountries.com1/v2/name/germany')
            let country = await response.json();
            return country[0];
        }

        asyncFunct()
        .then(x => console.log("asyncFunct ", x))
        .catch(y => console.log("asyncFunct ", y))

    </script>

</body>
</html>